// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:rent_bill_maker/models/bill/bill_model.dart';
import 'package:rent_bill_maker/models/property/property_model.dart';
import 'package:rent_bill_maker/models/tenant/tenant_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BillModelAdapter());
    registerAdapter(DateSystemAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(PropertyModelAdapter());
    registerAdapter(TenantModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BillModelAdapter());
    registerAdapter(DateSystemAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(PropertyModelAdapter());
    registerAdapter(TenantModelAdapter());
  }
}
